// Hand-written per-city intro copy for Priority 5 of the SEO spec. Only 7
// cities exist right now, so these are written individually rather than
// templated - a shared template with the city name swapped in reads as
// boilerplate to both readers and search engines.
export const CITY_INTROS: Record<string, string> = {
  atlanta: `Atlanta has become one of the Southeast's most active bubble tea markets, with shops spread across the city core and into suburbs like Decatur, Marietta, Alpharetta, Duluth, Sandy Springs, and Roswell - all part of the greater Atlanta metro area, so you'll see plenty of them in this list even though they're technically their own towns. The scene here leans toward strong Asian-American culinary neighborhoods, particularly around Buford Highway and Duluth, where you'll find shops serving everything from classic Taiwanese milk tea to fruit-forward drinks and matcha. Whether you're near Midtown, in the northern suburbs, or out toward Gwinnett County, there's a boba shop within reach. Browse the listings below to compare ratings, hours, and menus, and filter by service options like delivery or dine-in to find the spot that fits your afternoon in Atlanta.`,

  chicago: `Chicago's bubble tea shops are scattered across the city's neighborhoods and into nearby suburbs like Evanston, Oak Park, Naperville, and Schaumburg, all of which count toward the greater Chicago metro area covered here. Chinatown and the neighborhoods along the Argyle Street corridor are especially dense with options, but you'll find solid boba spots from the Loop out to the western and northern suburbs. Chicago's drink scene tends to mix Taiwanese-style milk teas with a growing number of shops experimenting with brown sugar boba, cheese foam, and fruit tea blends. Winters here make a hot milk tea just as popular as an iced one in summer. Use the filters below to narrow this list by rating, tags, or service options, and find a bubble tea shop near wherever you're headed in Chicago.`,

  dallas: `Dallas-Fort Worth's boba scene has grown quickly, with shops concentrated in Dallas proper and spilling into suburbs like Plano, Irving, Frisco, and Richardson - all part of the same metro area, which is why you'll see them listed here alongside Dallas shops. Plano and Richardson in particular have strong Asian-American communities and a correspondingly high concentration of tea shops, ranging from long-running local chains to newer specialty cafes. Given how spread out the metro is, most people here drive to their favorite shop rather than walk, so filtering by neighborhood and checking hours before you go is worth the extra step. Browse the list below to compare shops across Dallas and its suburbs, sort by rating or distance, and find your next bubble tea stop.`,

  'new-york': `New York City's bubble tea scene spans all five boroughs, and you'll see shops here from Manhattan, Brooklyn, Queens, the Bronx, and Staten Island grouped together as one metro area. Flushing and Manhattan's Chinatown remain the city's biggest concentrations of boba shops, but you'll find strong options in Sunset Park, Bay Ridge, and plenty of neighborhoods that don't traditionally get associated with bubble tea at all - it's genuinely everywhere in New York now. Between subway commutes and the sheer density of options, most New Yorkers have a go-to shop within a few blocks of home or work. Use the filters below to sort by borough-adjacent tags, rating, or service options like delivery, and find a bubble tea shop near you in New York.`,

  philadelphia: `Philadelphia's bubble tea shops cluster around Chinatown and University City, with the metro area covered here also including nearby New Jersey communities like Camden and Cherry Hill, plus Pennsylvania suburbs like King of Prussia - which is why some of the shops on this list show a New Jersey address even though they're part of the Philadelphia area. The city's large student population around Penn and Drexel keeps demand high for both classic milk tea and newer fruit-tea and slush options, and you'll find shops that stay open late to match. Whether you're downtown, out toward the Main Line, or across the river in South Jersey, there's a boba shop covered in this directory. Filter the list below by tags or rating to find the right one for you.`,

  seattle: `Seattle's bubble tea shops run from downtown and the University District out through the Eastside suburbs of Bellevue, Redmond, Kirkland, and Renton, all part of the greater Seattle metro area featured in this list. It's not a coincidence that a city this attached to coffee has also embraced boba - many Seattle-area shops blend the two, offering espresso-based drinks alongside classic milk teas. The tech-heavy Eastside suburbs in particular have a dense concentration of shops catering to the daytime office crowd, while University District shops lean toward the student schedule. Wherever you are in the Seattle area, use the filters below to sort by rating, hours, or service options and find a bubble tea shop nearby.`,

  washington: `The Washington, D.C. bubble tea scene extends well beyond the district itself, and this list includes nearby Maryland communities like Bethesda and Silver Spring along with Virginia communities like Arlington and Alexandria - all part of the same D.C. metro area, which is why some shops here show a Maryland or Virginia address instead of "Washington." Rockville and the broader Route 355 corridor in Maryland, along with Arlington's Clarendon and Ballston neighborhoods in Virginia, are particularly strong for boba given their large Asian-American populations. If you commute across the district line for work, there's a good chance your favorite shop is a Metro ride away rather than a walk. Browse the listings below and filter by rating or tags to find a bubble tea shop anywhere in the D.C. area.`,
}
